import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

export function renderTailwindSafelist(classes: string[]): string {
  const sorted = Array.from(new Set(classes)).sort((a, b) => a.localeCompare(b));
  const lines = [
    "# LMNAs deterministic Tailwind safelist",
    "# Generated by content-importer; do not edit manually.",
    ...sorted,
    ""
  ];

  return `${lines.join("\n")}`;
}

export async function writeTailwindSafelistFile(filePath: string, classes: string[]): Promise<{ path: string; lineCount: number }> {
  const content = renderTailwindSafelist(classes);
  await mkdir(path.dirname(filePath), { recursive: true });

  let current: string | null = null;
  try {
    current = await readFile(filePath, "utf8");
  } catch {
    current = null;
  }

  if (current !== content) {
    await writeFile(filePath, content, "utf8");
  }

  return {
    path: filePath,
    lineCount: Math.max(content.trim().split(/\r?\n/).length - 2, 0)
  };
}
