import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { renderTailwindSafelist, writeTailwindSafelistFile } from "../import/tailwindSafelist.js";

const tempDirs: string[] = [];

afterEach(async () => {
  while (tempDirs.length > 0) {
    const dir = tempDirs.pop();
    if (dir) {
      await rm(dir, { recursive: true, force: true });
    }
  }
});

async function createTempDir(): Promise<string> {
  const dir = await mkdtemp(path.join(os.tmpdir(), "tailwind-safelist-test-"));
  tempDirs.push(dir);
  return dir;
}

describe("tailwindSafelist", () => {
  it("renders deterministic sorted output", () => {
    const content = renderTailwindSafelist(["text-base", "p-4", "p-4", "bg-white"]);

    expect(content).toBe(
      "# LMNAs deterministic Tailwind safelist\n# Generated by content-importer; do not edit manually.\nbg-white\np-4\ntext-base\n"
    );
  });

  it("writes byte-identical safelist content for repeated runs", async () => {
    const dir = await createTempDir();
    const filePath = path.join(dir, "tailwind.safelist.txt");

    await writeTailwindSafelistFile(filePath, ["p-4", "text-base", "bg-white"]);
    const first = await readFile(filePath, "utf8");

    await writeTailwindSafelistFile(filePath, ["text-base", "bg-white", "p-4"]);
    const second = await readFile(filePath, "utf8");

    expect(second).toBe(first);
  });
});
